import 'dart:async';

import 'package:supabase_flutter/supabase_flutter.dart';

class AppUserProfile {
  const AppUserProfile({
    required this.id,
    required this.email,
    this.displayName,
    this.department,
    this.phoneNumber,
    this.streetAddress,
    this.barangay,
    this.city,
    this.bio,
    this.avatarUrl,
    this.shareCode,
  });

  final String id;
  final String email;
  final String? displayName;
  final String? department;
  final String? phoneNumber;
  final String? streetAddress;
  final String? barangay;
  final String? city;
  final String? bio;
  final String? avatarUrl;

  /// Read-only code others use to follow this user's shared events.
  /// Generated by the database; intentionally left out of [toJson] so
  /// profile upserts never overwrite it.
  final String? shareCode;

  String get initials {
    final source = (displayName?.trim().isNotEmpty == true ? displayName : email)
        ?.trim();
    if (source == null || source.isEmpty) {
      return 'B';
    }

    final parts = source.split(RegExp(r'\s+')).where((part) => part.isNotEmpty).toList();
    if (parts.isEmpty) {
      return source.substring(0, 1).toUpperCase();
    }

    if (parts.length == 1) {
      return parts.first.substring(0, 1).toUpperCase();
    }

    return '${parts.first.substring(0, 1)}${parts.last.substring(0, 1)}'.toUpperCase();
  }

  factory AppUserProfile.fromJson(Map<String, dynamic> json) {
    return AppUserProfile(
      id: json['id'] as String,
      email: json['email'] as String,
      displayName: json['display_name'] as String?,
      department: json['department'] as String?,
      phoneNumber: json['phone_number'] as String?,
      streetAddress: json['street_address'] as String?,
      barangay: json['barangay'] as String?,
      city: json['city'] as String?,
      bio: json['bio'] as String?,
      avatarUrl: json['avatar_url'] as String?,
      shareCode: json['share_code'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'email': email,
      'display_name': displayName,
      'department': department,
      'phone_number': phoneNumber,
      'street_address': streetAddress,
      'barangay': barangay,
      'city': city,
      'bio': bio,
      'avatar_url': avatarUrl,
    };
  }
}

abstract class AppAuthService {
  Stream<bool> authStateChanges();
  bool get isSignedIn;
  AppUserProfile? get currentUser;
  Future<void> signIn({required String email, required String password});
  Future<void> signUp({
    required String email,
    required String password,
    String? displayName,
    String? department,
  });
  Future<void> updateDisplayName(String displayName);

  /// The current user's share code, creating a profile row when needed.
  Future<String?> fetchShareCode();

  /// Follows the calendar behind [code]; returns a label for the owner
  /// (e.g. "Juan Dela Cruz • Mayor's Office") on success.
  Future<String> joinSharedCalendar(String code);

  Future<void> signOut();
  Future<void> dispose();
}

class SupabaseAuthService implements AppAuthService {
  SupabaseAuthService(this._client);

  final SupabaseClient _client;

  @override
  Stream<bool> authStateChanges() {
    return _client.auth.onAuthStateChange.map((state) => state.session != null);
  }

  @override
  bool get isSignedIn => _client.auth.currentSession != null;

  @override
  AppUserProfile? get currentUser {
    final user = _client.auth.currentUser;
    if (user == null) {
      return null;
    }

    return AppUserProfile(
      id: user.id,
      email: user.email ?? '',
      displayName: user.userMetadata?['display_name'] as String?,
      department: user.userMetadata?['department'] as String?,
      avatarUrl: user.userMetadata?['avatar_url'] as String?,
    );
  }

  Future<AppUserProfile?> fetchUserProfile() async {
    try {
      final user = _client.auth.currentUser;
      if (user == null) {
        return null;
      }

      final response = await _client
          .from('profiles')
          .select()
          .eq('id', user.id)
          .single();

      return AppUserProfile.fromJson(response);
    } catch (e) {
      // Profile doesn't exist yet, return basic profile from auth
      return currentUser;
    }
  }

  Future<void> createOrUpdateProfile(AppUserProfile profile) async {
    try {
      await _client.from('profiles').upsert(
        profile.toJson(),
        onConflict: 'id',
      );

      // Keep auth metadata in sync so currentUser reflects the latest
      // name/department without an extra profile fetch.
      if (_client.auth.currentUser != null) {
        await _client.auth.updateUser(
          UserAttributes(
            data: {
              'display_name': profile.displayName,
              'department': profile.department,
            },
          ),
        );
      }
    } catch (e) {
      print('Error saving profile: $e');
      rethrow;
    }
  }

  @override
  Future<void> signIn({required String email, required String password}) async {
    await _client.auth.signInWithPassword(
      email: email,
      password: password,
    );
  }

  @override
  Future<void> signUp({
    required String email,
    required String password,
    String? displayName,
    String? department,
  }) async {
    final metadata = <String, dynamic>{
      if (displayName != null && displayName.isNotEmpty) 'display_name': displayName,
      if (department != null && department.isNotEmpty) 'department': department,
    };

    final response = await _client.auth.signUp(
      email: email,
      password: password,
      data: metadata.isEmpty ? null : metadata,
    );

    // Create profile entry
    if (response.user != null) {
      await createOrUpdateProfile(
        AppUserProfile(
          id: response.user!.id,
          email: email,
          displayName: displayName,
          department: department,
        ),
      );
    }
  }

  @override
  Future<void> updateDisplayName(String displayName) async {
    final user = _client.auth.currentUser;
    if (user == null) return;

    // Update auth metadata
    await _client.auth.updateUser(
      UserAttributes(
        data: {'display_name': displayName},
      ),
    );

    // Update profiles table
    await createOrUpdateProfile(
      AppUserProfile(
        id: user.id,
        email: user.email ?? '',
        displayName: displayName,
      ),
    );
  }

  @override
  Future<String?> fetchShareCode() async {
    final user = _client.auth.currentUser;
    if (user == null) return null;

    Future<String?> selectCode() async {
      final row = await _client
          .from('profiles')
          .select('share_code')
          .eq('id', user.id)
          .maybeSingle();
      return row?['share_code'] as String?;
    }

    var code = await selectCode();
    if (code == null) {
      // No profile row yet — create one so the database generates a code.
      final profile = currentUser;
      if (profile != null) {
        await createOrUpdateProfile(profile);
        code = await selectCode();
      }
    }
    return code;
  }

  @override
  Future<String> joinSharedCalendar(String code) async {
    final rows = await _client.rpc(
      'join_shared_calendar',
      params: {'code': code},
    ) as List<dynamic>;

    if (rows.isEmpty) {
      return 'this calendar';
    }

    final row = rows.first as Map<String, dynamic>;
    final name = (row['owner_name'] as String?)?.trim();
    final department = (row['owner_department'] as String?)?.trim();
    final parts = [
      if (name != null && name.isNotEmpty) name,
      if (department != null && department.isNotEmpty) department,
    ];
    return parts.isEmpty ? 'this calendar' : parts.join(' • ');
  }

  @override
  Future<void> signOut() async {
    await _client.auth.signOut();
  }

  @override
  Future<void> dispose() async {}
}

class MemoryAuthService implements AppAuthService {
  MemoryAuthService._(this._signedIn, this._currentUser) {
    _controller.add(_signedIn);
  }

  factory MemoryAuthService.signedIn() {
    return MemoryAuthService._(
      true,
      const AppUserProfile(
        id: 'mock-user-id',
        email: 'user@example.com',
        displayName: 'Barangay Officer',
        department: "Mayor's Office",
      ),
    );
  }

  factory MemoryAuthService.signedOut() {
    return MemoryAuthService._(false, null);
  }

  final StreamController<bool> _controller = StreamController<bool>.broadcast();
  bool _signedIn;
  AppUserProfile? _currentUser;

  @override
  Stream<bool> authStateChanges() async* {
    yield _signedIn;
    yield* _controller.stream;
  }

  @override
  bool get isSignedIn => _signedIn;

  @override
  AppUserProfile? get currentUser => _currentUser;

  @override
  Future<void> signIn({required String email, required String password}) async {
    _signedIn = true;
    _currentUser = AppUserProfile(id: 'mock-user-id', email: email, displayName: email.split('@').first);
    _controller.add(true);
  }

  @override
  Future<void> signUp({
    required String email,
    required String password,
    String? displayName,
    String? department,
  }) async {
    _signedIn = true;
    _currentUser = AppUserProfile(
      id: 'mock-user-id',
      email: email,
      displayName: displayName?.isNotEmpty == true ? displayName : email.split('@').first,
      department: department,
    );
    _controller.add(true);
  }

  @override
  Future<void> updateDisplayName(String displayName) async {
    final current = _currentUser;
    if (current == null) {
      return;
    }
    _currentUser = AppUserProfile(
      id: current.id,
      email: current.email,
      displayName: displayName,
      department: current.department,
      phoneNumber: current.phoneNumber,
      streetAddress: current.streetAddress,
      barangay: current.barangay,
      city: current.city,
      bio: current.bio,
      avatarUrl: current.avatarUrl,
    );
    _controller.add(true);
  }

  @override
  Future<String?> fetchShareCode() async => 'ABC123';

  @override
  Future<String> joinSharedCalendar(String code) async {
    if (code.trim().isEmpty) {
      throw Exception('Invalid share code');
    }
    return "Juan Dela Cruz • Mayor's Office";
  }

  @override
  Future<void> signOut() async {
    _signedIn = false;
    _currentUser = null;
    _controller.add(false);
  }

  @override
  Future<void> dispose() async {
    await _controller.close();
  }
}
